development:
  db: 0
  host: localhost
  port: 6379
  namespace: tlr_dev
  redis: redis://localhost:6379/0/tlr_dev
test:
  db: 1
  host: localhost
  port: 6379
  namespace: tlr_test
  redis: redis://localhost:6379/1/tlr_test
staging:
  db: 0
  host: localhost
  port: 6379
  namespace: tlr_stg
  redis: redis://localhost:6379/0/tlr_stg
production:
  db: 0
  host: localhost
  port: 6379
  namespace: tlr_prod
  redis: redis://localhost:6379/0/tlr_prod
