queue_city_tweets:
  cron: "0 */2 * * *"
  class: QueueCityTweets
  queue: high
  args:
  description: "Get entries from Chatham to tweet out"


city_post_tweet:
  cron: "0 0,1,16,17,18,19,20,21,22,23 * * 1-5"
  class: CityPostTweet
  queue: high
  args:
  description: "Post a tweet for cities 6 times a day during the week"

