development:
  adapter: mongodb
  host: localhost
  database: localread_vanity
staging:
  adapter: mongodb
  host: localhost
  database: localread_vanity
production:
  adapter: mongodb
  host: localhost
  database: localread_vanity
